Update and release
- Web Server available
- more parameters added for summary
- On server only one jobs runs after each other (kind of basic queuing system)

diff --git a/protParamWrapServer b/protParamWrapServer
--- a/protParamWrapServer
+++ b/protParamWrapServer
@@ -4,9 +4,97 @@
 # ARG_HELP([The general script's help msg])
 # ARG_OPTIONAL_REPEATED([include],[I],[Directory for temporary folders],['/tmp'])
 
-# ARGBASH_GO
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
 
+
+die()
+{
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
+}
+
+
+begins_with_short_option()
+{
+	local first_option all_short_options='shI'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_sequence=
+_arg_include=('/tmp')
+
+
+print_help()
+{
+	printf '%s\n' "The general script's help msg"
+	printf 'Usage: %s [-s|--sequence <arg>] [-h|--help] [-I|--include <arg>]\n' "$0"
+	printf '\t%s\n' "-s, --sequence: sequence file in .fasta format, including all sequences to process (no default)"
+	printf '\t%s\n' "-h, --help: Prints help"
+	printf '\t%s' "-I, --include: Directory for temporary folders (default array elements:"
+	printf " '%s'" '/tmp'
+	printf ')\n'
+}
+
+
+parse_commandline()
+{
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-s|--sequence)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_sequence="$2"
+				shift
+				;;
+			--sequence=*)
+				_arg_sequence="${_key##--sequence=}"
+				;;
+			-s*)
+				_arg_sequence="${_key##-s}"
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			-I|--include)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_include+=("$2")
+				shift
+				;;
+			--include=*)
+				_arg_include+=("${_key##--include=}")
+				;;
+			-I*)
+				_arg_include+=("${_key##-I}")
+				;;
+			*)
+				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				;;
+		esac
+		shift
+	done
+}
+
+parse_commandline "$@"
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
+
 
 #### Variables
 SECONDS=0
@@ -18,6 +106,24 @@ sequenceNameNoExt=$(echo $_arg_sequence | cut -d "." -f 1)
 timeNeed () {
 ELAPSED="$(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
 printf "|%-30s%30s|\n" "Program finished within:" "$ELAPSED"
+}
+
+queue () {
+#checks if protparam is already running and wait until finished to avoid multi running on server
+emptyFormat="|%-60s|\n"
+while true; do
+        top -b -n 1 -u ricci > temprunner
+        running=$(cat temprunner | grep julia)
+        if [[ -z "$running" ]]; then
+                rm -r $WPATH/* >/dev/null 2>/dev/null
+                break
+        else
+                echo full
+                printf "$emptyFormat" "       another job is still running!"
+                printf "$emptyFormat" "        job will start automatically!"
+                sleep 1m
+        fi
+done
 }
 
 check () {
@@ -122,7 +228,7 @@ mv *-data.txt dataFiles >/dev/null 2>/dev/null
 printf "|%-60s|\n" "..."
 }
 
-### SCRIPT 
+### SCRIPT
 runScript () {
 seperateFasta
 protParam
@@ -131,5 +237,6 @@ getData
 cleanUp
 timeNeed
 }
+queue
 check
 # ] <-- needed because of Argbash
